version: '3.3'

services:
      wordpress_db:
            container_name: wordpress_db
            image: mariadb:latest
            ports:
                  - "3306:3306"
            volumes:
                  - ./mariadb/:/var/lib/mysql
            restart: always
            environment:
                  MYSQL_ROOT_PASSWORD: Admin#123^
                  MYSQL_DATABASE: wordpress_db
                  MYSQL_USER: wordpress
                  MYSQL_PASSWORD: Admin#123^
            networks:
                  - wordpress-network

      wordpress_wp:
            container_name: wordpress_wp
            image: wordpress:latest
            volumes:
                  - ./public/:/var/www/html
            environment:
                  WORDPRESS_DB_HOST: wordpress_db:3306
                  WORDPRESS_DB_NAME: wordpress_db
                  WORDPRESS_TABLE_PREFIX: wp_dev_
                  WORDPRESS_DB_PASSWORD: Admin#123^
            ports:
                  - "8080:80"
            links:
                  - wordpress_db
            restart: always
            networks:
                  - wordpress-network

      wordpress_phpmyadmin:
            container_name: wordpress_phpmyadmin
            image: phpmyadmin/phpmyadmin:latest
            ports:
                  - "8090:80"
            links:
                  - wordpress_db
            restart: always
            environment:
                  - PMA_ARBITRARY=1
                  - PMA_HOST=wordpress_db
            volumes:
                  - /sessions
            networks:
                  - wordpress-network
networks:
  wordpress-network:
      driver: bridge
