version: '3.3'

services:
      wordpress_portainer:
            image: portainer/portainer-ce:alpine
            container_name: wordpress_portainer
            hostname: wordpress_portainer
            # environment:
            #      privileged: true
            volumes:
                  - /var/run/docker.sock:/var/run/docker.sock
                  - ./wordpress_portainer/data:/data
            ports:
                  - 9000:9000
            networks:
                  - wordpress-network

      wordpress_db:
            container_name: wordpress_db
            hostname: wordpress_db
            image: mariadb:latest
            ports:
                  - "3306:3306"
            volumes:
                  - ./wordpress_mariadb:/var/lib/mysql
            restart: always
            environment:
                  MYSQL_ROOT_PASSWORD: Admin#123^
                  MYSQL_DATABASE: wordpress_db
                  MYSQL_USER: wordpress
                  MYSQL_PASSWORD: Admin#123^
                  TZ: Asia/Shanghai
            networks:
                  - wordpress-network

      wordpress_wp:
            container_name: wordpress_wp
            hostname: wordpress_wp
            image: wordpress:latest
            volumes:
                  - ./wordpress_wp/public:/var/www/html
            environment:
                  WORDPRESS_DB_HOST: wordpress_db:3306
                  WORDPRESS_DB_USER: wordpress      
                  WORDPRESS_DB_NAME: wordpress_db
                  WORDPRESS_TABLE_PREFIX: wp_dev_
                  WORDPRESS_DB_PASSWORD: Admin#123^
            ports:
                  - "8080:80"
            links:
                  - wordpress_db
            restart: always
            networks:
                  - wordpress-network

      # wordpress_phpmyadmin:
      #       container_name: wordpress_phpmyadmin
      #       hostname: wordpress_phpmyadmin
      #       image: phpmyadmin:latest
      #       ports:
      #             - "8090:80"
      #       links:
      #             - wordpress_db
      #       restart: always
      #       environment:
      #             - PMA_ARBITRARY=1
      #             - PMA_HOST=wordpress_db
      #             - PMA_USER=wordpress
      #             - PMA_PASSWORD=Admin#123^
      #       volumes:
      #             - ./wordpress_phpmyadmin/sessions:/sessions
      #             - ./wordpress_phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      #       networks:
      #             - wordpress-network
networks:
      wordpress-network:
            driver: bridge
